# Generated by Django 6.0.2 on 2026-02-20 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tankstatus',
            old_name='last_updated',
            new_name='last_heartbeat',
        ),
        migrations.RenameField(
            model_name='tankstatus',
            old_name='pump_status',
            new_name='pump_running',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tankstatus',
            name='current_level',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='tankstatus',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='water_tank.device'),
        ),
    ]
