# Generated by Django 6.0.2 on 2026-02-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tank', '0002_rename_last_updated_tankstatus_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('is_executed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='water_tank.device')),
            ],
        ),
    ]
