# Generated by Django 6.0.2 on 2026-03-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tank', '0003_pumpschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=101),
        ),
    ]
