# Generated by Django 6.0.2 on 2026-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tank', '0004_alter_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankstatus',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
