# Generated by Django 6.0.3 on 2026-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_tank', '0005_tankstatus_is_online_alter_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankstatus',
            name='current_level',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
